version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "chaos"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17rd64tjszxxi"
s3_prefix = "chaos"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
